import type { Metadata } from 'next'
import { Karla } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'

const karla = Karla({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RebeApp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
